asset: app.zip
tap: getstream/getstream-cli/app.rb
template: |
    class App < Formula
      desc     "$REPO_DESCRIPTION"
      homepage "$REPO_WEBSITE"
      version  "$STABLE_VERSION"
      url      "$STABLE_ASSET_URL"
      sha256   "$STABLE_ASSET_SHA256"

      def install
        prefix.install "app"
      end
    end
